version: '3.8'

services:
  # Ton application (Le Producteur de données)
  api:
    build: .
    container_name: devops-api
    ports:
      - "8000:8000"
    volumes:
      - ./firebase-key.json:/app/firebase-key.json

  # Le système de surveillance (Le Consommateur de données)
  prometheus:
    image: prom/prometheus
    container_name: devops-prometheus
    ports:
      - "9090:9090" 
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml 